### ISSUE TITLE
Error when i using tsc to build my app with dependence (ts-automapper) to tiny docker image

### ISSUE THREAD

**Issue by lucianoscastro** [MADEiN83/ts-automapper#24]
I using TypeScript with nodejs, and the way was imported the interfaces AutoMapperTypes, AutoMapperOptions cause build fail on TSC.

![failBuild](https://user-images.githubusercontent.com/43710761/141313117-cd1a75d0-a4e5-4522-9f0d-2ccfe15abc40.png)

You can replace 

 ```
import { AutoMapperTypes, AutoMapperOptions } from "core/interfaces"; 
```

for 

 ```
import { AutoMapperTypes, AutoMapperOptions } from "./core/interfaces"; 
```

And fix this issue :) 

ps.
Your project is the best of automapper package for node js.

**Comment by MADEiN83** [comment]
Hi @lucianoscastro!
I'll check your concern ASAP ;-)

Thanks a lot for your feedback!!

**Comment by MADEiN83** [comment]
I've just pushed a new minor [version (1.2.1)](https://www.npmjs.com/package/ts-automapper)!
